version: '3.1'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 7_db_1
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123456
    volumes:
        - ./data:/var/lib/postgresql/data
