version: '3.1'
services:
  db:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: app
      POSTGRES_DB: app
    volumes:
        - ./data:/var/lib/postgresql/data